name: parenting_advisor
description: A parenting advice chatbot using Gemini AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true